services:
  - type: web
    name: oblique-strategies
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    autoDeploy: true
    buildCommand: npm run build
    startCommand: npm start
